#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     liftLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servoGate,               tServoNormal)
#pragma config(Servo,  srvo_S1_C2_2,    hookLeft,               tServoNormal)
#pragma config(Servo,  srvo_S1_C2_3,    hookRight,               tServoNormal)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "util.h"
#include "lift.h"

task main(){
	waitForStart();
	nMotorEncoder[liftLeft] = 0;
	nMotorEncoder[liftRight] = 0;   

	while(true){
    	// Drive controls
        motor[leftDrive] = joystickValue(1, 1, 2);
        motor[rightDrive] = joystickValue(1, 2, 2);

        // Lift controls
        if(joy1Btn(CONTROLLER_A)){
            if(nMotorEncoder[liftLeft] < THIRTY_LIFT){
                liftMove(THIRTY_LIFT, true);
            }else if(nMotorEncoder[liftLeft] > THIRTY_LIFT){
                liftMove(THIRTY_LIFT, false);
            }else{
                //nothing
            }
        } else if(joy1Btn(CONTROLLER_B)){
            if(nMotorEncoder[liftLeft] < SIXTY_LIFT){
                liftMove(SIXTY_LIFT, true);
            }else if(nMotorEncoder[liftLeft] > SIXTY_LIFT){
                liftMove(SIXTY_LIFT, false);
            }else{
                //nothing
            }
        } else if(joy1Btn(CONTROLLER_X)){
            if(nMotorEncoder[liftLeft] < NINETY_LIFT){
                liftMove(NINETY_LIFT, true);
            }else if(nMotorEncoder[liftLeft] > NINETY_LIFT){
                liftMove(NINETY_LIFT, false);
            }else{
                //nothing
            }
        } else if(joy1Btn(CONTROLLER_Y)){
            if(nMotorEncoder[liftLeft] < GOAL_LIFT){
                liftMove(GOAL_LIFT, true);
            }else if(nMotorEncoder[liftLeft] > GOAL_LIFT){
                liftMove(GOAL_LIFT, false);
            }else{
                //nothing
            }
        }

        //Back hook Controls
        if(joystick.joy1_TopHat == DPAD_UP){
            hook(true);
        }else if(joystick.joy1_TopHat == DPAD_DOWN){
            hook(false);
        }

        //Gate Controls
        if(joystick.joy1_TopHat == DPAD_LEFT){
            gate(true);
        }else if(joystick.joy1_TopHat == DPAD_RIGHT){
            gate(false);
        }
    }
}
