#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     HTANG,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     liftLeft,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     liftRight,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    gateFront,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    gateBack,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    hookLeft,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    hookRight,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "util.h"
#include "lift.h"
#include "autonomous3.h"
#include "drivers/hitechnic-angle.h"

task main()
{
	HTANGresetAccumulatedAngle(HTANG);
	while(true){
		if(joy1Btn(CONTROLLER_A)){
			HTANGresetAccumulatedAngle(HTANG);
		}
		writeDebugStreamLine("Cumulative: %d", HTANGreadAccumulatedAngle(HTANG));
	}

}
