#pragma config(Sensor, S1,     ir,             sensorHiTechnicIRSeeker600)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while (true) {
		nxtDisplayTextLine(0, "S:%d", SensorValue[ir]);
		nxtDisplayTextLine(1, "R:%d", SensorRaw[ir]);
	}
}
