#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     irLeft,         sensorI2CCustom)
#pragma config(Sensor, S3,     irRight,        sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rotator,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftTread,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     rightTread,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    extender,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    flagExtender,         tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-irseeker-v2.h"

task main() {
	// Set the DSP mode
	while(true) {
		if (HTIRS2setDSPMode(irRight, DSP_600))
			break;
	}

	while (true) {
		int dirEnhanced;
		int strEnhanced;

		HTIRS2readEnhanced(irLeft, dirEnhanced, strEnhanced);

		nxtDisplayTextLine(0, "DC:%d", HTIRS2readDCDir(irRight)); // non-modulated
		nxtDisplayTextLine(1, "AC:%d", HTIRS2readACDir(irRight)); // modulated
		nxtDisplayTextLine(2, "ENH:%d,%d", dirEnhanced, strEnhanced);
	}
}
