#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,     irLeft,         sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S3,     irRight,        sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S4,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rotator,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftTread,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     rightTread,    tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    extender,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    flagExtender,         tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Copyright (c) 2013 AJ Stubberud. All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/

#include "JoystickDriver.c" // I have no idea where waitForStart() is declared....
#include "lib/gyro.h"

#define DRIVE_SPEED 50
#define TURN_SPEED 75
#define QUARTER_TURN_TIME 800

task main() {
	waitForStart();

	long timeForward;

	calibrateGyro();

	ClearTimer(T1);

	// Raise the arm
	motor[rotator] = 100;
	wait1Msec(2750);
	motor[rotator] = 0;

	// Drive forward until we get a sensor reading of 8
	motor[leftDrive] = DRIVE_SPEED;
	motor[rightDrive] = DRIVE_SPEED;
	while (true) {
		writeDebugStreamLine("%d", SensorValue[irRight]);
		if (time1[T1] > 10000) {
			motor[leftDrive] = 0;
			motor[rightDrive] = 0;
			PlaySound(soundException);
			StopAllTasks();
		} else if (SensorValue[irRight] == 8) {
			// Stop driving forward, time to rotate
			timeForward = time1[T1];
			break;
		}
	}
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;

	// Turn 90 degrees to the right
	turnRight(90.0, TURN_SPEED);

	// Eject the block
	motor[leftTread] = -60;
	motor[rightTread] = -60;
	wait1Msec(3000);
	motor[leftTread] = 0;
	motor[rightTread] = 0;

	// Raise the arm some more
	motor[rotator] = 100;
	wait1Msec(500);
	motor[rotator] = 0;

	// Turn back 90 degrees
	turnLeft(80.0, TURN_SPEED);

	// Drive back to the wall
	motor[leftDrive] = -DRIVE_SPEED;
	motor[rightDrive] = -DRIVE_SPEED;
	wait1Msec(timeForward);
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;

	// Turn right again
	turnRight(90.0, TURN_SPEED);

	// Drive forward
	motor[leftDrive] = 100;
	motor[rightDrive] = 100;
	wait1Msec(1000);
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;

	turnLeft(55.0, 50);
	motor[leftDrive] = 100;
	motor[rightDrive] = 100;
	wait1Msec(2000);
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}
