#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     liftLeft,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     liftRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    gateFront,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    gateBack,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    hookLeft,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    hookRight,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "util.h"
#include "lift.h"
#include "autonomous3.h"

//RAMP AUTONOMOUS

void initializeRobot(){
	nMotorEncoder[liftLeft] = 0;
	nMotorEncoder[liftRight] = 0;
	servo[hookLeft] = 182;
	servo[hookRight] = 79;
	servo[gateFront] = 0;
	servo[gateBack] = 255;
	hook(true);
	return;
}

task main(){
	initializeRobot();
	waitForStart();

	//drive backwards off the ramp
	driveBackward(2500, 20);
	//keep driving
	//driveBackward(1000);
	//stop infront of the tube67
	//driveStop();
	//hook the tube
	//hook(false);
	//raise the arm
	//liftMove(SIXTY_LIFT, true);
	//open the gate
	//turn
	//turnEuler(35, 35, false);
	//drive forward to the goal
	//driveForward(4000);

}
