#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     driveLeft,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     liftLeft,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     driveRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftRight,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servoGate,               tServoNormal)
#pragma config(Servo,  srvo_S1_C2_2,    hookLeft,               tServoNormal)
#pragma config(Servo,  srvo_S1_C2_3,    hookRight,               tServoNormal)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "util.h"
#include "lift.h"
#include "autonomous3.h"

//TOWER AUTONOMOUS
int sonarvalue = 0;
void autoStraight();

//if the end goal is straight ahead
void autoStraight(){
	while (SensorValue[Sonar] > 15){
		motor[motorLeft] = 20;
		motor[motorRight] = 20;
	}
	motor[motorLeft] = 0;
	motor[motorRight]= 0;
}

void initializeRobot(){
	calibrateGyro();

	//RESET SERVOS

	return;
}

task main()
{
	initializeRobot();
	waitForStart();
	while(true){
		sonarvalue = SensorValue[Sonar];
		if(sonarvalue == 255){
			//Diagonal center console
			//The ultrasonic sensor cannot detect diagonal surfaces - therefore, it returns 255 as its default value.
			nxtDisplayCenteredTextLine(3, "Diagonal, %d", sonarvalue);
		}else if(SensorValue[Sonar] < 105){
			//goal is straight ahead
			nxtDisplayCenteredTextLine(3, "Ahead, %d", sonarvalue);
			autoStraight();
			break;
		}else{
			//goal is sideways
			nxtDisplayCenteredTextLine(3, "Sideways, %d", sonarvalue);
		}
	}
	PlaySoundFile("attention.rso");
}
