#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "autonomous3.h"
#include "util.h"

int power = 50;
int degrees = 90;

task main()
{
	calibrateGyro();
	while(true){
		writeDebugStreamLine("R1 for Right Turn");
		writeDebugStreamLine("L1 for Left Turn");
		while(true){
			if(joy1Btn(CONTROLLER_R1)){
				writeDebugStreamLine("R1, L1 for Power");
				writeDebugStreamLine("R2, L2 for Degrees");
				writeDebugStreamLine("A to confirm");
				while(true){
					if(joy1Btn(CONTROLLER_R1)){
						power += 5;
						writeDebugStreamLine("power = %d", power);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_R2)){
						degrees += 5;
						writeDebugStreamLine("degrees = %d", degrees);
					 	wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_L1)){
						power -= 5;
						writeDebugStreamLine("power = %d", power);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_L2)){
						degrees -= 5;
						writeDebugStreamLine("degrees = %d", degrees);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_A)){
						wait1Msec(500);
						break;
					}
				}
				calibrateGyro();
				turnEuler(degrees, power, false);
			writeDebugStreamLine("R1 for Right Turn");
			writeDebugStreamLine("L1 for Left Turn");
			}
			if(joy1Btn(CONTROLLER_L1)){
				writeDebugStreamLine("R1, L1 for Power");
				writeDebugStreamLine("R2, L2 for Degrees");
				writeDebugStreamLine("A to confirm");
				while(true){
					if(joy1Btn(CONTROLLER_R1)){
						power += 5;
						writeDebugStreamLine("power = %d", power);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_R2)){
						degrees += 5;
						writeDebugStreamLine("degrees = %d", degrees);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_L1)){
						power -= 5;
						writeDebugStreamLine("power = %d", power);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_L2)){
						degrees -= 5;
						writeDebugStreamLine("degrees = %d", degrees);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_A)){
						wait1Msec(500);
						break;
					}
				}
				calibrateGyro();
				turnEuler(degrees, power, true);
			writeDebugStreamLine("R1 for Right Turn");
			writeDebugStreamLine("L1 for Left Turn");
			}
		}
	}
}
