#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightDrive,    tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "autonomous3.h"
#include "util.h"

bool flag = true;

task main()
{
	/*
	while(true){
		if (joy1Btn(CONTROLLER_L1)){
			turnLeftEuler(90, 100);
		}
		else if(joy1Btn(CONTROLLER_R1)){
			turnRightEuler(90, 100);
		}
	}
	*/
	float rotated = 0;
	float lastTime;
	int speed = 25;
	int degrees = 35;
	calibrateGyro();
	motor[leftDrive] = -speed;
	motor[rightDrive] = speed;

	lastTime = nSysTime;

	while (abs(rotated) < degrees) {
		float g_val = gyroValue();
		float dt = nSysTime - lastTime;
		lastTime = nSysTime;
		rotated += (dt/1000) * g_val;
		writeDebugStreamLine("rotated %f", rotated);
		writeDebugStreamLine("time %f", dt);
		writeDebugStreamLine("gval %f", g_val);
	}
	writeDebugStreamLine("-----------------------");
	driveStop();
}
