#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Copyright (c) 2014 Jake Lee, Team 4790

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

#include "autonomous3.h"
#include "util.h"

int power = 50;
int degrees = 90;

task main()
{
	calibrateGyro();
	while(true){
		writeDebugStreamLine("R1 for Right Turn");
		writeDebugStreamLine("L1 for Left Turn");
		while(true){
			if(joy1Btn(CONTROLLER_R1)){
				writeDebugStreamLine("R1, L1 for Power");
				writeDebugStreamLine("R2, L2 for Degrees");
				writeDebugStreamLine("A to confirm");
				while(true){
					if(joy1Btn(CONTROLLER_R1)){
						power += 5;
						writeDebugStreamLine("power = %d", power);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_R2)){
						degrees += 5;
						writeDebugStreamLine("degrees = %d", degrees);
					 	wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_L1)){
						power -= 5;
						writeDebugStreamLine("power = %d", power);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_L2)){
						degrees -= 5;
						writeDebugStreamLine("degrees = %d", degrees);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_A)){
						wait1Msec(500);
						break;
					}
				}
				calibrateGyro();
				turnEuler(degrees, power, false);
			writeDebugStreamLine("R1 for Right Turn");
			writeDebugStreamLine("L1 for Left Turn");
			}
			if(joy1Btn(CONTROLLER_L1)){
				writeDebugStreamLine("R1, L1 for Power");
				writeDebugStreamLine("R2, L2 for Degrees");
				writeDebugStreamLine("A to confirm");
				while(true){
					if(joy1Btn(CONTROLLER_R1)){
						power += 5;
						writeDebugStreamLine("power = %d", power);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_R2)){
						degrees += 5;
						writeDebugStreamLine("degrees = %d", degrees);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_L1)){
						power -= 5;
						writeDebugStreamLine("power = %d", power);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_L2)){
						degrees -= 5;
						writeDebugStreamLine("degrees = %d", degrees);
						wait1Msec(500);
					}
					if(joy1Btn(CONTROLLER_A)){
						wait1Msec(500);
						break;
					}
				}
				calibrateGyro();
				turnEuler(degrees, power, true);
			writeDebugStreamLine("R1 for Right Turn");
			writeDebugStreamLine("L1 for Left Turn");
			}
		}
	}
}
